# Generated by Django 5.1.7 on 2025-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ionUser",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("ion_username", models.CharField(max_length=100)),
            ],
        ),
    ]
